name: Build AIX Extension

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build App Inventor Extension
        uses: pavi2410/AIX-Action@main
        with:
          package-name: 'com.haroon.applovinmax'

      - name: Upload AIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppLovinMaxExtension
          path: ./**/*.aix
